[theme]
base="light"
primaryColor="#007bff"  # Biru Khas Instansi Pemerintah
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8F9FA" # Abu-abu sangat muda untuk kontras
textColor="#343A40"
font="sans serif"
